"""config.py — Single source of truth for paths, hyperparameters, and seeds.

The entire paper recipe (Li, Erickson & Xiong, 2022) lives here. Scripts and
modules in `src/` import from this file; no values are hardcoded elsewhere.

What the PAPER says vs. what WE decided is marked in the comments.
Deviations from the paper are also documented in DEVIATIONS.md.
"""
from __future__ import annotations

import os
from pathlib import Path

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
# Dataset root folder: contains one subfolder per animal (cattle_XXXX/).
# Resolved in priority order:
#   1. Environment variable CATTLE_DATA_DIR (manual override).
#   2. Typical Kaggle paths (/kaggle/input/.../BeefCattle_Muzzle_Individualized).
#   3. Local extraction for smoke-test (data_local/...), searching upwards
#      from this file (also works inside a git worktree).
_DATASET_DIRNAME = "BeefCattle_Muzzle_Individualized"

# Project root = folder containing this config.py.
PROJECT_ROOT = Path(__file__).resolve().parent


def _find_dataset_dir() -> Path:
    """Returns the first valid path that contains the dataset."""
    # 1. Environment override.
    env = os.environ.get("CATTLE_DATA_DIR")
    if env:
        return Path(env)

    candidates: list[Path] = []

    # 2. Kaggle: the dataset may be under any slug in /kaggle/input.
    kaggle_input = Path("/kaggle/input")
    if kaggle_input.is_dir():
        # direct match .../<slug>/BeefCattle_Muzzle_Individualized
        candidates += list(kaggle_input.glob(f"*/{_DATASET_DIRNAME}"))
        # in case the slug IS the dataset
        candidates += list(kaggle_input.glob(f"*/*/{_DATASET_DIRNAME}"))
        # recursive fallback: mount may be deeper, e.g.
        # /kaggle/input/datasets/<user>/<slug>/BeefCattle_Muzzle_Individualized
        deep = next(kaggle_input.rglob(_DATASET_DIRNAME), None)
        if deep is not None:
            candidates.append(deep)

    # 3. Local: data_local/ at the project root or in parent repos (worktree).
    for base in [PROJECT_ROOT, *PROJECT_ROOT.parents]:
        candidates.append(base / "data_local" / _DATASET_DIRNAME)
        candidates.append(base / "data" / _DATASET_DIRNAME)

    for c in candidates:
        if c.is_dir():
            return c

    # Fallback: return the expected local path even if it doesn't exist yet,
    # so the error message points to something concrete.
    return PROJECT_ROOT / "data_local" / _DATASET_DIRNAME


DATA_DIR = _find_dataset_dir()

# Outputs (everything generated by the pipeline).
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
SPLITS_DIR = OUTPUTS_DIR / "splits"
CHECKPOINTS_DIR = OUTPUTS_DIR / "checkpoints"
RESULTS_DIR = OUTPUTS_DIR / "results"
LOGS_DIR = OUTPUTS_DIR / "logs"
AUG_CACHE_DIR = OUTPUTS_DIR / "aug_cache"   # precomputed synthetic images (see scripts/04)

# --------------------------------------------------------------------------- #
# Dataset (values verified by file count in Phase 0; match the paper)
# --------------------------------------------------------------------------- #
NUM_CLASSES = 268          # PAPER: 268 cattle = 268 classes. Confirmed in Phase 0.
EXPECTED_IMAGES = 4923     # PAPER: 4923 images. Confirmed in Phase 0.
# PAPER: min=4 / max=70. Verified by file count in Phase 0: matches.
# (There are 8 classes with 4 images; the paper mentions only 4 IDs — see DEVIATIONS.md.)
MIN_IMAGES_PER_CLASS = 4
MAX_IMAGES_PER_CLASS = 70

# --------------------------------------------------------------------------- #
# Splits (PAPER: 65/15/20, per image, stratified, reshuffle)
# --------------------------------------------------------------------------- #
TRAIN_FRAC = 0.65
VAL_FRAC = 0.15
TEST_FRAC = 0.20
SPLIT_SEED = 42            # OUR CHOICE: fixed seed for the split (reproducible).

# --------------------------------------------------------------------------- #
# Preprocessing / transforms (PAPER)
# --------------------------------------------------------------------------- #
IMAGE_SIZE = 300          # PAPER: 300×300 (NOT 224).
# PAPER: normalize to [0,1] raw (ToTensor already does this). Does NOT use ImageNet mean/std.
USE_IMAGENET_NORM = False  # OUR CHOICE: flag for experiments; default OFF (paper).
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

# Data augmentation (PAPER, train only).
AUG_BRIGHTNESS = (0.2, 0.5)   # ColorJitter brightness factor.
AUG_ROTATION_DEG = 15         # RandomRotation [-15, +15].
AUG_BLUR_KERNELS = (1, 3, 5)  # GaussianBlur kernel ∈ {1,3,5}.

# ADDITIVE augmentation (see DEVIATIONS D4). PAPER: augmentation "creates synthetic images
# and enlarges the dataset", KEEPING the originals (especially for classes with few images).
# It does NOT replace each image as typical online augmentation does.
# Per class, expand up to min(AUG_TARGET_CAP, AUG_FACTOR * N_i) by adding augmented copies;
# classes with >= AUG_TARGET_CAP images are left unchanged.
AUG_TARGET_CAP = 20   # OUR CHOICE: per-class cap after expansion.
AUG_FACTOR = 2        # OUR CHOICE: at most double the class images.

# --------------------------------------------------------------------------- #
# Training (PAPER)
# --------------------------------------------------------------------------- #
EPOCHS = 50
OPTIMIZER = "sgd"
MOMENTUM = 0.9
LR = 0.001
LR_STEP_SIZE = 7          # StepLR step_size.
LR_GAMMA = 0.1            # StepLR gamma.
FREEZE_BACKBONE = True    # PAPER: fine-tune ONLY the FC layers (frozen backbone).

# OUR CHOICES (not specified by the paper, see DEVIATIONS.md):
BATCH_SIZE = 32           # reduce if OOM with 300×300 + VGG16_BN.
NUM_WORKERS = 4
REPLICATE_SEEDS = (0, 1, 2)  # 3 replicates → mean ± std. Reduced from 5 due to
                             # 12-hour T4 budget (see DEVIATIONS.md D2). This way
                             # `02_train_vgg.py` without --seeds fits in a single commit.

# --------------------------------------------------------------------------- #
# Weighted Cross-Entropy
# --------------------------------------------------------------------------- #
# PAPER: w_i = N_max / N_i, with N_max=70 (dataset maximum).
# We compute weights from the TRAIN split (no leakage): N_i = count in train,
# N_max = maximum of those counts (≈46, because train ≈65% of the class with 70 images).
# N_max is only a GLOBAL scaling factor for the loss; the relative weight between classes
# (N_max/N_i) is what matters and is preserved. To force the paper's literal value (70)
# for comparison, set the override. See DEVIATIONS.md.
WCE_NMAX_OVERRIDE: int | None = None  # None = empirical from train (≈46).

# --------------------------------------------------------------------------- #
# Models
# --------------------------------------------------------------------------- #
MODELS = ("vgg16_bn", "resnet50")  # vgg16_bn = replicates the paper; resnet50 = own backbone.

# ImageNet pretrained weights. To avoid depending on internet on Kaggle, download
# once and upload as a Kaggle Dataset; models.py loads them from here.
# Canonical torchvision names (do NOT rename the .pth files):
PRETRAINED_FILES = {
    "vgg16_bn": "vgg16_bn-6c64b313.pth",
    "resnet50": "resnet50-0676ba61.pth",
}


def _find_pretrained_dir() -> Path | None:
    """Folder containing the pretrained .pth files, or None (→ downloaded on demand).

    Order: env CATTLE_PRETRAINED_DIR → /kaggle/input/*/ (where the .pth files are) →
    local pretrained_weights/ (in the project or parent repos / worktree).
    """
    env = os.environ.get("CATTLE_PRETRAINED_DIR")
    if env:
        return Path(env)

    any_file = next(iter(PRETRAINED_FILES.values()))
    candidates: list[Path] = []

    kaggle_input = Path("/kaggle/input")
    if kaggle_input.is_dir():
        # Kaggle folder containing the .pth (at any reasonable depth)
        candidates += [p.parent for p in kaggle_input.glob(f"*/{any_file}")]
        candidates += [p.parent for p in kaggle_input.glob(f"*/*/{any_file}")]
        # recursive fallback: mount may be deeper
        # (/kaggle/input/datasets/<user>/<slug>/...).
        deep = next(kaggle_input.rglob(any_file), None)
        if deep is not None:
            candidates.append(deep.parent)

    for base in [PROJECT_ROOT, *PROJECT_ROOT.parents]:
        candidates.append(base / "pretrained_weights")
        # ...or any immediate subfolder containing the .pth files (detected by
        # FILENAME, same as Kaggle): also works with imagenet-pretrained/.
        candidates += [p.parent for p in base.glob(f"*/{any_file}")]

    for c in candidates:
        if (c / any_file).is_file():
            return c
    return None


PRETRAINED_DIR = _find_pretrained_dir()

# --------------------------------------------------------------------------- #
# STAGE 2 — CMPD300 dataset (SOURCE, muzzle) — cross-modality baseline
# --------------------------------------------------------------------------- #
# CMPD300 already comes split into folders: <CMPD300_DIR>/{train,val,test}/<ID>/*.JPG
# NOT re-split here. `scripts/00_inspect_cmpd300.py` reads those folders and generates
# split JSONs + label_map (same {"path","label"} format used by src/dataset.py).
# Note: IDs are NOT contiguous and val does not have all classes (reported by the script).
_CMPD300_DIRNAME = "Baseline"   # folder containing train/ val/ test/


def _find_cmpd300_dir() -> Path:
    """First valid path with CMPD300 (env → Kaggle → local datasets/)."""
    env = os.environ.get("CMPD300_DATA_DIR")
    if env:
        return Path(env)

    candidates: list[Path] = []

    kaggle_input = Path("/kaggle/input")
    if kaggle_input.is_dir():
        candidates += list(kaggle_input.glob(f"*/{_CMPD300_DIRNAME}"))
        candidates += list(kaggle_input.glob(f"*/*/{_CMPD300_DIRNAME}"))
        deep = next(kaggle_input.rglob(f"{_CMPD300_DIRNAME}/train"), None)
        if deep is not None:
            candidates.append(deep.parent)

    for base in [PROJECT_ROOT, *PROJECT_ROOT.parents]:
        candidates.append(base / "datasets" / _CMPD300_DIRNAME)

    for c in candidates:
        if (c / "train").is_dir():
            return c

    return PROJECT_ROOT / "datasets" / _CMPD300_DIRNAME


CMPD300_DIR = _find_cmpd300_dir()
CMPD300_SPLITS_DIR = OUTPUTS_DIR / "splits_cmpd300"   # split JSONs + label_map for CMPD300

# Stage 2 preprocessing (our decision, not the paper's recipe). 224 + ImageNet norm:
# matches what the pretrained backbone expects and is lighter than 300. THE SAME
# preprocessing is applied to the target domain (Ahmed faces) to avoid inflating the
# gap with a preprocessing mismatch. To compare with the paper's recipe, switch to
# IMAGE_SIZE_S2=300 / USE_IMAGENET_NORM_S2=False.
IMAGE_SIZE_S2 = 224
USE_IMAGENET_NORM_S2 = True


# --------------------------------------------------------------------------- #
# STAGE 3 — Unsupervised cross-dataset re-ID by clustering (muzzle → muzzle)
# --------------------------------------------------------------------------- #
# New field = a second muzzle dataset presented WITHOUT labels. A frozen encoder
# embeds it, DBSCAN/HDBSCAN discovers the identities (estimating how many there are),
# and we measure the partition against the real labels (ARI/NMI). Labels are used
# ONLY to evaluate, never to cluster. See the Stage 3 plan for the full framing.
#
# TARGET_DIR: root of the unlabelled muzzle dataset (one folder per real individual,
# used only for evaluation). By default it is the Zenodo Muzzle DB (`DATA_DIR`), but
# it is overridable so the source encoder (trained on CMPD300) meets DISJOINT identities.
TARGET_DIR = Path(os.environ.get("CATTLE_TARGET_DIR", str(DATA_DIR)))

# DINOv2 (frozen, self-supervised generic baseline). HuggingFace model id.
# dinov2-base = 768-d embedding; good speed/quality trade-off for a first pass.
DINOV2_MODEL = os.environ.get("DINOV2_MODEL", "facebook/dinov2-base")

# Preprocessing for ViT/foundation encoders (their native recipe, NOT the paper's):
# resize shortest side then center-crop, ImageNet normalization. Documented in DEVIATIONS.
VIT_RESIZE = 256
VIT_CROP = 224

# Clustering (DBSCAN over cosine distance on L2-normalized embeddings).
# eps is the ONE hyperparameter to fix WITHOUT looking at labels. We report the whole
# grid so its sensitivity is visible, plus HDBSCAN (auto, no eps) as the primary estimator.
DBSCAN_EPS_GRID = (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50)
DBSCAN_MIN_SAMPLES = 2      # a core point needs >=1 other neighbour within eps.
HDBSCAN_MIN_CLUSTER_SIZE = 2

# Retrieval (kNN) evaluation runs on the honest session single-shot split.
REID_SEED = 0


def ensure_output_dirs() -> None:
    """Create output directories if they do not exist."""
    for d in (SPLITS_DIR, CHECKPOINTS_DIR, RESULTS_DIR, LOGS_DIR, CMPD300_SPLITS_DIR):
        d.mkdir(parents=True, exist_ok=True)


def as_dict() -> dict:
    """Serializable snapshot of the config (for logging with each run)."""
    return {
        k: (str(v) if isinstance(v, Path) else v)
        for k, v in globals().items()
        if k.isupper() and not k.startswith("_")
    }


if __name__ == "__main__":
    import json

    print(f"PROJECT_ROOT : {PROJECT_ROOT}")
    print(f"DATA_DIR     : {DATA_DIR}  (exists: {DATA_DIR.is_dir()})")
    print(json.dumps(as_dict(), indent=2, ensure_ascii=False))
